# railway.toml - Replace the entire content with this code
[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "always"
startCommand = "python server.py"
